language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -e .
- cd develop
- python manage.py migrate
script:
- python manage.py test reacttools
- cd ..
deploy:
  provider: pypi
  user: __token__
  password: pypi-AgEIcHlwaS5vcmcCJDc4ZGUyMzdjLTZhYTAtNGY3My1hNmQ2LTgzOTk4YTg5NWFiZgACQ3sicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJkamFuZ28tcmVhY3QtdG9vbHMiXX0sICJ2ZXJzaW9uIjogMX0AAAYgQW8WI7znYB0InXH6VoKTl4ordNFjFholgjCroEcmY3M