language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -e .
- cd develop
- python manage.py migrate
script:
- python manage.py test reacttools
- cd ..
deploy:
  provider: pypi
  user: __token__
  password:
    secure: ZQgRusv0Lc3iJszkeW/mg3as6AqxwDAzGM5pf82NyyyInXr+GswmaKf9G0xMKgHUljjv8QHpW1uW0ESwvkxaB//zwZyXaur1MZyzuiWBs+wB2at6jPTnORAPpr2kKPpSwe7hGwjwEfmMMqkxNwVZFkgZHhsF56R6HAzkLYBMoMLIHY6iOiX9lqSQC8qNRPL+OeZSTCgUSyMXfSZnbMexBchr4rwTldutVXwKw8nLJ0b6Th9r95//nzC03d8M0vBwgzVMhPoX/889vhcl6KDCaDN2hfU/UoG6o4G8wbWVwwixW7r/pOJa00TH9S8YcqS42kj6R7ni1OthEI/0KAoDyzd3Cgi2Oc3irx9TGIkVgvNzHuqOT9xt6mTL7OepLxHr44BfV3QT54jnMpSIxVnXSX+sOo7XaMQyUBzhcisoc7cC3Wc0jF0pD7mMyNuNkVhWt4ozBtrNAoZPTSjFE/Fjs24+Y+xXbcpU/eaQE+VPUwje6gdza7zmuD1jc8e8TLUPHsfWDKP6U3Kw5aVP2Ds6jvy24ihgg/nwmm95/8T2Gmk9mjcwTCVPSkQ8iJkKu5qJKIlnOhgYoNy+yRX1LFZykrXdVYVcwKcdVKMdvDHUPaFJ3txHqvXfJI2XJnTQvdpHuX4GUBS9F/8u6nAWDaPGhOHmjEYmUAB/8HaIKzpI4L8=
