language: python
python:
- '3.7'
install:
- pip install -e .
- cd develop
- python manage.py migrate
script:
- python manage.py test reacttools
- cd ..
deploy:
  provider: pypi
  user: __token__
  password:
    secure: hnZok5fFSYQs1n5Q3Fz5QllGlqUf+DThhKsVe0mMVxmhio4416g4QBK54Ac5wovMVjGbqOZG5bwXQvJeYnqGUAbS2V1CwhVc5WE8MZeEXvat+5kygXWpaIntU7jd8zKj5LkTzXoQfvMl1z1GMTi7ru63J65ZhNOykhO9V/lFZy+dUM6l7n6ne8smjDSf/SexQuM8XvzuI348i7GexvxhaZKS0lptt+DaSM4IyA6xb/fEZrWyHRHuBWY9ZCvOnjcSzaoA1AiifqcTa9kZxrmI3mXPzCtGhBn1ng0xRfC455BfsHN/N6vFUlfO7za6A/YfFwXagtoePLvtzxM+GPY7EuCKDmxu5AX6c3J01Axukbau1BxMQAg3CLrOF706DSzQQV0N0W4hbcEcPcDIYcJcwi1u1B81tKqb1nFe5cvHfhSsNDk8lXavrhkC38JzVZ0Pj7MXqC3DURHW2ISrtV9XO/PkdjuQ7sl8wzZo8a81NTLgomgUJ4NAtG19WLXf/RiVWF2UVCwcpUwKn69wBW9W3FSpLYsFMV7eyK2wtlpw0AmEBncMRbMW6AkDoVjTivYHGAUyjVeyHbsdLeVNA+3Zb5z3J7u2Oj0kCPPcV+1MI4i6mdmoZKvLZAVeEFaImWA36X+rtbv2yGMH3dVtSH/NBJFMOjYPQqZ4Wr1yiImD5N0=
