language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -e .
- cd develop
- python manage.py migrate
script:
- python manage.py test reacttools
- cd ..
deploy:
  provider: pypi
  user: __token__
  password:
    secure: FYdirEzabIGv3SzVUt8nvheziTLfa884mSi7f/7sMAAgeijHOWVclO3uDJegydSR4Ku8HY974aCS/m9zuzhnIGPr/+Y/e8OhqbHpHMPgv/ZypkY+Mjo3EeMDf0D0O05GgFMnNk+RhW3XY7jrI308vPu98+Sj4FeKBo7cewEHZ/FPpfAcAa+imVjMTEc/xbROnkyfJM3jnGL+67gRNvDIj2rCWGmzz6JsMrKtfDAa+s6zbpvX1tVytM28xI8cL9PcsqOq/ZCxFI0D0qFJspo5LdTqEwGyidnkDpRNOW9hgNQPvPDtKPX5SH/cYEI5wDVhqLLmvtACjyRVNCT818ai75iaFskEGPq3iYEeQB+uPIeNn7iBcnwjTsvltQZr9nb1r4L4G3zoK4QlRLLihoIEJ5w1i5WCO/QKG1oEiUYyPurt4u6xO2tcnDZstZbZ2Weat9X6JKyS5JT5cN147UTSb9CV7J0CzBuSaXcyDY5gzEbZZbI5a4VsA01L97MgwBn7Cm6YdiM+mTWr1uhk243PFDL2R0OzPOnWxTo2OVr3Eq5nVTAsNwarle9OuojXl3rXvMzBHN2RPeCdoXqqXyc5wojRa2Io89MfNllWtaxiaVGFAdSTRouZAhSd1epHq2FC1XM69JIqODBhHe/qVKzkYpATxt3FoheTTwhYGOJXq54=
